name: Build Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v4
      with:
        go-version: 1.22.1  # Specify the Go version you are using

    - name: Install dependencies
      run: |
        cd backend
        go mod download

    - name: Build backend
      run: |
        cd backend
        go build -v ./...

    - name: Verify build
      run: |
        cd backend
        go test -v ./...
